name: SpriteVC Publish
run-name: ${{ github.ref_name }} Publish

on:
    release:
        types: [published]
    
jobs:
    publish_extension:
        name: Publish Extension
        runs-on: ubuntu-latest

        steps:
          - name: Checkout Repo
            id: checkout_repo
            uses: actions/checkout@v4
            with:
              submodules: recursive
        
          - name: Create Extension
            id: create_extension
            run: python publish.py extension none zip publish/

          - name: Retrieve Release
            id: retrieve_release
            uses: octokit/request-action@v2.x
            env:
                GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
            with:
                route: GET /repos/${{ github.repository }}/releases/tags/${{ github.ref }}

          - run: echo "HELLO ${{ fromJson(steps.retrieve_release.outputs.data).id }}"

          - name: Publish Asset
            id: publish_asset 
            uses: octokit/request-action@v2.x
            env:
                GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
            with:
                route: POST /repos/${{ github.repository }}/releases/{release_id}/assets?name=spritevc.aseprite-extension
                release_id: ${{ fromJson(steps.retrieve_release.outputs.data).id }}
                body: $(cat publish/spritevc.aseprite-extension) 
                  
                

          
