name: SpriteVC Publish
run-name: ${{ github.ref_name }} Publish

on:
    release:
        types: [published]

jobs:
    publish_extension:
        name: Publish Extension
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
          - name: Checkout Repo
            id: checkout_repo
            uses: actions/checkout@v4
            with:
              submodules: recursive
        
          - name: Create Extension
            id: create_extension
            run: python publish.py extension none zip publish/

          - name: Retrieve Release
            id: retrieve_release
            uses: octokit/request-action@v2.x
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
                route: GET /repos/${{ github.repository }}/releases/tags/${{ github.ref_name }}

          - name: Publish Asset
            id: publish_asset 
            run: |
              curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -H "Content-Type: application/octet-stream" \
              "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ fromJson(steps.retrieve_release.outputs.data).id }}/assets?name=spritevc.aseprite-extension" \
              --data-binary "@publish/spritevc.aseprite-extension"
                

          
