name: Test SpriteVC

on:
    push: {}

jobs:
    test_extension:
        name: Test Extension
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
            - name: Build image
              run: docker-compose build test
            - name: Run tests
              run: docker-compose run --rm test
