name: Test SpriteVC

on:
    push: {}

jobs:
    test_extension:
        name: Test Extension
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              id: checkout
              uses: actions/checkout@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Build image
              id: docker_build
              uses: docker/build-push-action@v5
              with:
                context: .
                cache-from: type=gha
                cache-to: type=gha,mode=max
                load: true
                file: test-docker/Dockerfile
                tags: test
            - name: Run tests
              id: test_run
              run: docker-compose run --rm spritevc-test
